import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PageHeader from "~/components/Layout/PageHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Rupesh Profile",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-primary text-tertiary mx-0 sm:mx-20">
                <PageHeader />
                {children}
            </body>
        </html>
    );
}
